input_queue_size: 1
output_queue_size: 1
cloud_filter_chain:
  - name: PassThroughFilter
    type: point_cloud2_filters/PassThroughFilterPointCloud2
    params:
      active: True
      input_frame: "base_link"
      output_frame: "rgb_camera_link"
      keep_organized: True
      negative: False
      filter_field_name: "y"
      filter_limit_min: -0.5
      filter_limit_max: 2
  - name: VoxelGridFilter
    type: point_cloud2_filters/VoxelGridFilterPointCloud2
    params:
      active: true
      input_frame: "base_link"
      output_frame: "rgb_camera_link"
      leaf_size_x: 0.05
      leaf_size_y: 0.05
      leaf_size_z: 0.05
      min_points_per_voxel: 10
      downsample_all_data: False
      filter_field_name: "x"
      filter_limit_min: -5
      filter_limit_max: 5
      negative: False
  - name: robot_body_filter_containment
    type: robot_body_filter/RobotBodyFilterPointCloud2
    params:
      sensor/min_distance: 0.05
      sensor/max_distance: 3
      sensor/point_by_point: false
      frames/fixed: base_link
      frames/sensor: rgb_camera_link
      frames/filtering: rgb_camera_link
      frames/output: rgb_camera_link
      body_model/inflation/scale: 1.1
      body_model/inflation/padding: 0.05
      body_model/robot_description_param: robot_description
      filter/do_clipping: false
      filter/do_contains_test: true
      filter/do_shadow_test: false
      transforms/timeout/unreachable: 0.3
      transforms/require_all_reachable: false