idmp_rleng: 1.8
idmp_tree_hl_min: 0.025
idmp_tree_hl_max: 6.4
idmp_tree_hl_clust: 0.05
idmp_tree_hl_init: 3.2
idmp_map_scale: 1024
idmp_obs_skip: 10
idmp_filt_outl: True

idmp_depth_input: False
idmp_dual_cam: False
idmp_pub_pcl: False
idmp_depth_topic: "/camera_1/depth/image_raw"
idmp_dual_depth_topic: ""
# idmp_pcl_topic: "/camera_2/depth/color/points"
# idmp_world_frame: "base_link"
idmp_pcl_topic: "/camera/depth_registered/points"
idmp_dynamic: False
idmp_fusion: True

idmp_dyn_tresh: 0.05
idmp_fus_min: 0.0005
idmp_fus_max: 0.005
