idmp_rleng: 1.8
idmp_tree_hl_min: 0.025
idmp_tree_hl_max: 12.8
idmp_tree_hl_clust: 0.05
idmp_tree_hl_init: 3.2
idmp_map_scale: 225
idmp_obs_skip: 10
idmp_filt_outl: False

idmp_pub_pcl: True
idmp_world_frame: "world"
idmp_pcl_topic: "/camera_2/depth/color/points"
idmp_caminfo_topic:
  - ["/camera_2/depth/camera_info", "camera_2_depth_optical_frame"]
idmp_dynamic: True
idmp_fusion: False

idmp_dyn_tresh: 0.01
idmp_fus_min: 0.0005
idmp_fus_max: 0.005
