gpis_rleng: 1.8
gpis_tree_hl_min: 0.025
gpis_tree_hl_max: 3.2
gpis_tree_hl_clust: 0.05
gpis_tree_hl_init: 1.6
gpis_map_scale: 1024
gpis_obs_skip: 10
gpis_filt_vox: 0.1
gpis_filt_outl: False

gpis_depth_input: False
gpis_dual_cam: False
gpis_pub_pcl: True
gpis_depth_topic: "/camera_1/depth/image_raw"
gpis_dual_depth_topic: ""
gpis_world_frame: "base_link"
# gpis_pcl_topic: "/camera/depth/color/points_crop"
# gpis_pcl_topic: "/zed2i/zed_node/point_cloud/cloud_registered"
gpis_pcl_topic: "/points_filt"
gpis_caminfo_topic: "/bullet/camera_info"
gpis_dynamic: True
gpis_fusion: False

gpis_dyn_tresh: 0.08
gpis_fus_min: 0.0005
gpis_fus_max: 0.01
